---
- hosts: kibana-node
  become: yes
  roles:
    - { role: geerlingguy.kibana, kibana_elasticsearch_url: "http://192.168.78.21:9200", kibana_server_port: 5601, kibana_server_host: "0.0.0.0", kibana_version: "6.2.4" }
